---
title: "Problem Set 4"
subtitle: "Due date: 16 October"
format: 
  html:
    self-contained: true
toc: true
editor: visual
execute: 
  echo: true
---

Please upload your completed assignment to the ELMs course site (under the assignments menu). Remember to include an annotated script file for all work with R and show your math for all other problems (if applicable, or necessary). Please also upload your completed assignment to the Github repository that you have shared with us. *We should be able to run your script with no errors.*

**Total points: 30**

## Question 1

*Points: 5*

::: {.callout-tip title="HG comments"}
3/5
:::

Suppose I am playing poker with a regular deck of 52 cards. I have three cards in my hand, one of which is a king. What is the probability that the next two cards I draw will both be kings?

**Answer:**

There are three kings left in the deck since one is in your hand already. So for the first card the probability will be 3/51. For the next card it will be 2/50. So to find the probability it would be 3/51 x 2/50 = 1/425 or 0.2353%

::: {.callout-tip title="HG comments"}
I start with a regular deck of 52 cards, which contains four Kings. I draw three cards, one of which is a King. Therefore, the remaining deck contains 49 cards, three of which are Kings.

The probability that I draw a King in my next draw is:

$$
Pr(K_1) = \frac{3}{49}
$$

Because there are three Kings remaining in my remaining deck of 49 cards (52 minus the three cards I have in my hand).

If I successfully draw a King in that draw, the probability that I draw a King in the next draw is:

$$
Pr(K_2) = \frac{2}{48}
$$

Because there are two Kings remaining in my remaining deck of 48 cards (52 minus the four cards I have in my hand).

Therefore, the probability that the next two cards I draw will both be kings is:

$$
Pr(K_1) \& Pr(K_2) = \frac{3}{49} * \frac{2}{48} = \frac{6}{2352} = 0.00255
$$
:::

## Question 2

*Points: 5*

::: {.callout-tip title="HG comments"}
5/5
:::

A survey of 1,500 randomly selected individuals reveals that 46% of them have a college degree and that 31% of them have a gun in their house. If you were to assume that college graduation and gun ownership are independent of one another, what is the probability that an individual is both a college graduate and does not have a gun in his or her house?

**Answer:**

100% - 31% = 69% of people that do not own a gun. So we take the percentage of college graduates times the percentage of people who do not own a gun, .46 x .69 = .3174. So probability would be 31.74 %.

## Question 3

*Points: 5*

::: {.callout-tip title="HG comments"}
5/5
:::

I roll a fair six-sided dice and I get a number greater than three. What is the probability that the next two dice rolls will also generate numbers greater than three?

**Answer:**

The probability of rolling a number greater than 3 is 3/6 or 1/2 since there are only three potential outcomes (4,5, and 6). The probability for the next role would be 1/2 as well so to find the probability for both events you multiply 1/2 x 1/2 = 1/4. So the probability would be 25%.

## Question 4

*Points: 10*

::: {.callout-tip title="HG comments"}
6/10
:::

Assume that in the United States, 15% of people are smokers and, of smokers, 60% smoke at least one pack a day. Among those who smoke at least a pack a day, 60% will develop lung cancer at some point in their lives while, in the rest of the population (which includes smokers who smoke less than a pack a day and non-smokers), only 10% will. What is the probability that a person who develops lung cancer was a smoker who smoked at least a pack a day?

**Answer:**

P(C) = P(C\|S) x P(S) + P(C\|N) x P(N)

P(C) = (.6 x .15) + (.10 x (1 - 0.15))

P(C) = 0.175

P(S\|C) = P(C) x P(S) / P\|C)

P(S\|C) = .60 x .15/ .175

P(S\|C) = .5143

Probability ofthat a person who develops lung cancer was a smoker who smoked at least a pack a day is around 51.43 %

::: {.callout-tip title="HG comments"}
The answer is 37.24%. Imagine that we have a population of 100 people.

-   15 people (15% of that population) smoke.

    -   9 people (60% of those 15 smokers) smoke at least one pack a day.

        -   5.4 of those 9 people who smoke at least one pack a day (60% of those who smoke at least one pack a day) will develop lung cancer at some point in their lives.

-   85 people (the remaining 85% of the population) do not smoke.

-   91 people smoke less than a pack a day or do not smoke (6 people smoke, but smoke less than one pack a day and 85 people do not smoke).

    -   9.1 of these people (10%) will develop lung cancer at some point in their lives.

-   14.5 people (5.4 people who smoke at least one pack a day and 9.1 people who do not smoke or smoke less than one pack a day) develop lung cancer at some point in their lives.

    -   5.4 of those people smoked at least a pack a day.

-   What is the probability that a person who develops lung cancer was a smoker who smoked at least a pack a day?

    -   Of the 14.5 people who developed lung cancer, 5.4 smoked at least a pack a day. Therefore, the probability that a person who develops lung cancer was a smoker who smoked at least a pack a day is 37.24%.
:::

P(S) = Probability of being a smoker is .15

P(C) = Probability of developing lung cancer

P(C\|S) = Probability that a smoker will develop lung cancer is .60

P(C\|N) = probability that a person is a non-smoker and develop lung cancer is .10

P(N) = probability somebody is a non smoker is .85

P(S\|C), which is the probability that a person is a smoker given that they develop lung cancer.

## Question 5

*Points: 5*

::: {.callout-tip title="HG comments"}
5/5
:::

Assume that in the world, 60% of countries are democracies and 80% of countries have ratified the Rome Statute for the International Criminal Court. Assume further that 90% of democracies have ratified the Rome Accords. What is the probability that a country is either a democracy or has ratified the Rome Accords?

**Answer:**

P(D or R) = P(D) + P(R) - P(D and R)

= .60 + .8 - .54

= .86

The Probability that a country either is a democracy or has ratified the Rome Statue is 86%

P(D) = Probability the country is a democracy is .6

P(R) = Probability the country has ratified the Rome statue is .8

P(D or R) = Probability that a country is either a democracy or has ratified the Rome Accords

P(D and R) = Probability that a country is both a democracy and has ratified the Rome Accords is .54 (P\|D x D)

P(D\|R) = Probability that a democracy has ratified the Rome Statue is .9
